[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.arduino.memory_type = qio_opi  
board_build.flash_mode = qio      
board_build.f_cpu = 240000000L
board_build.psram = enable
board_build.psram_mode = opi             

board_build.partitions = huge_app.csv       

build_flags = 
    -DCONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ=240
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM              
    -mfix-esp32-psram-cache-issue   
    -Os

upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    adafruit/DHT sensor library@^1.4.6