// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_DHT11_H
#define UI_DHT11_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_dht11
extern void ui_dht11_screen_init(void);
extern void ui_dht11_screen_destroy(void);
extern lv_obj_t * ui_dht11;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Labelrh;
extern lv_obj_t * ui_Labeltemp;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

