// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_dht11 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Labelrh = NULL;
lv_obj_t * ui_Labeltemp = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_dht11_screen_init(void)
{
    ui_dht11 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dht11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -136);
    lv_obj_set_y(ui_Label3, -108);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "TEMP");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x6500FE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Label3, lv_color_hex(0xFD0606), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_dht11);
    lv_obj_set_width(ui_Panel1, 150);
    lv_obj_set_height(ui_Panel1, 90);
    lv_obj_set_x(ui_Panel1, -81);
    lv_obj_set_y(ui_Panel1, -42);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_dht11);
    lv_obj_set_width(ui_Panel2, 150);
    lv_obj_set_height(ui_Panel2, 90);
    lv_obj_set_x(ui_Panel2, 81);
    lv_obj_set_y(ui_Panel2, -43);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -125);
    lv_obj_set_y(ui_Label4, -56);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Temp:");

    ui_Label10 = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 30);
    lv_obj_set_y(ui_Label10, -56);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "RH:");

    ui_Labelrh = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Labelrh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelrh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelrh, 81);
    lv_obj_set_y(ui_Labelrh, -56);
    lv_obj_set_align(ui_Labelrh, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelrh, "00.00");

    ui_Labeltemp = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Labeltemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labeltemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labeltemp, -63);
    lv_obj_set_y(ui_Labeltemp, -56);
    lv_obj_set_align(ui_Labeltemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labeltemp, "00.00");

    ui_Button7 = lv_btn_create(ui_dht11);
    lv_obj_set_width(ui_Button7, 62);
    lv_obj_set_height(ui_Button7, 39);
    lv_obj_set_x(ui_Button7, 123);
    lv_obj_set_y(ui_Button7, 92);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_dht11);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 123);
    lv_obj_set_y(ui_Label8, 93);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "back");

    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);

}

void ui_dht11_screen_destroy(void)
{
    if(ui_dht11) lv_obj_del(ui_dht11);

    // NULL screen variables
    ui_dht11 = NULL;
    ui_Label3 = NULL;
    ui_Panel1 = NULL;
    ui_Panel2 = NULL;
    ui_Label4 = NULL;
    ui_Label10 = NULL;
    ui_Labelrh = NULL;
    ui_Labeltemp = NULL;
    ui_Button7 = NULL;
    ui_Label8 = NULL;

}
