// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

// ==================== UI控件全局变量 ====================
lv_obj_t * ui_file = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label6 = NULL;

// 文件管理器专用控件（供外部访问）
lv_obj_t * ui_file_list = NULL;      // 文件列表容器
lv_obj_t * ui_path_label = NULL;     // 路径显示标签
lv_obj_t * ui_status_label = NULL;   // 状态栏标签
lv_obj_t * ui_refresh_btn = NULL;    // 刷新按钮
lv_obj_t * ui_title_label = NULL;    // 标题标签

// ==================== 事件函数 ====================
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen1_screen_init);
    }
}

// ==================== UI构建函数 ====================
void ui_file_screen_init(void)
{
    // ==================== 创建屏幕 ====================
    ui_file = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_file, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_file, lv_color_hex(0x1E1E1E), LV_STATE_DEFAULT);
    
    // ==================== 原有返回按钮（位置保持不变） ====================
    ui_Button4 = lv_btn_create(ui_file);
    lv_obj_set_width(ui_Button4, 57);
    lv_obj_set_height(ui_Button4, 30);
    lv_obj_set_x(ui_Button4, 128);
    lv_obj_set_y(ui_Button4, 100);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x5D2D2D), LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button4, 5, LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_file);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_Label6, 126);
    lv_obj_set_y(ui_Label6, 96);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "back");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    
    // ==================== 文件管理器UI控件 ====================
    
    // 标题标签
    ui_title_label = lv_label_create(ui_file);
    lv_label_set_text(ui_title_label, "FILE MANAGER");
    lv_obj_set_pos(ui_title_label, 15, 10);
    lv_obj_set_style_text_color(ui_title_label, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_title_label, &lv_font_montserrat_16, LV_STATE_DEFAULT);
    
    // 路径显示标签
    ui_path_label = lv_label_create(ui_file);
    lv_label_set_text(ui_path_label, "Path: /");
    lv_obj_set_pos(ui_path_label, 15, 35);
    lv_obj_set_style_text_color(ui_path_label, lv_color_hex(0xAAAAAA), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_path_label, &lv_font_montserrat_12, LV_STATE_DEFAULT);
    
    // 刷新按钮（右上角）
    ui_refresh_btn = lv_btn_create(ui_file);
    lv_obj_set_size(ui_refresh_btn, 40, 30);
    lv_obj_set_pos(ui_refresh_btn, 265, 5);
    lv_obj_set_style_bg_color(ui_refresh_btn, lv_color_hex(0x3D3D3D), LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_refresh_btn, 5, LV_STATE_DEFAULT);
    
    lv_obj_t *refresh_label = lv_label_create(ui_refresh_btn);
    lv_label_set_text(refresh_label, "R");
    lv_obj_center(refresh_label);
    lv_obj_set_style_text_color(refresh_label, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    
    // 状态栏标签（底部）
    ui_status_label = lv_label_create(ui_file);
    lv_label_set_text(ui_status_label, "Ready");
    lv_obj_set_pos(ui_status_label, 15, 220);
    lv_obj_set_style_text_color(ui_status_label, lv_color_hex(0x88FF88), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_status_label, &lv_font_montserrat_12, LV_STATE_DEFAULT);
    
    // 文件列表容器
    ui_file_list = lv_obj_create(ui_file);
    lv_obj_set_size(ui_file_list, 290, 150);
    lv_obj_set_pos(ui_file_list, 15, 55);
    lv_obj_set_style_bg_color(ui_file_list, lv_color_hex(0x2D2D2D), LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_file_list, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_file_list, lv_color_hex(0x555555), LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_file_list, 5, LV_STATE_DEFAULT);
}

void ui_file_screen_destroy(void)
{
    if(ui_file) lv_obj_del(ui_file);

    // NULL screen variables
    ui_file = NULL;
    ui_Button4 = NULL;
    ui_Label6 = NULL;
    ui_file_list = NULL;
    ui_path_label = NULL;
    ui_status_label = NULL;
    ui_refresh_btn = NULL;
    ui_title_label = NULL;
}