// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include <string.h>

// 声明串口发送函数
extern void serial_send(const char *buf);

lv_obj_t * ui_SerialTool = NULL;
lv_obj_t * ui_PanelRX = NULL;
lv_obj_t * ui_labelrx = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Spinner1 = NULL;

// event funtions
void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // 返回功能保留
    if(event_code == LV_EVENT_KEY &&  lv_event_get_key(e) == LV_KEY_ESC) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }

    // ===================== 我加的：按√发送串口 + 清空 =====================
    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        uint16_t btn = lv_keyboard_get_selected_btn(ui_Keyboard1);
        const char *txt = lv_keyboard_get_btn_text(ui_Keyboard1, btn);

        if(strcmp(txt, LV_SYMBOL_OK) == 0)
        {
            const char *data = lv_textarea_get_text(ui_TextArea1);
            serial_send(data);               // 发送到串口
            lv_textarea_set_text(ui_TextArea1, ""); // 清空输入框
        }
    }
    // ====================================================================
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Label9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_SerialTool_screen_init(void)
{
    ui_SerialTool = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SerialTool, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelRX = lv_obj_create(ui_SerialTool);
    lv_obj_set_width(ui_PanelRX, 310);
    lv_obj_set_height(ui_PanelRX, 77);
    lv_obj_set_x(ui_PanelRX, 0);
    lv_obj_set_y(ui_PanelRX, 3);
    lv_obj_set_align(ui_PanelRX, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelRX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelrx = lv_label_create(ui_SerialTool);
    lv_obj_set_width(ui_labelrx, LV_SIZE_CONTENT);   /// 300
    lv_obj_set_height(ui_labelrx, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_labelrx, 4);
    lv_obj_set_y(ui_labelrx, -71);
    lv_obj_set_align(ui_labelrx, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_labelrx, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_labelrx, "                                                                        ");

    ui_TextArea1 = lv_textarea_create(ui_SerialTool);
    lv_obj_set_width(ui_TextArea1, 312);
    lv_obj_set_height(ui_TextArea1, 45);
    lv_obj_set_x(ui_TextArea1, 2);
    lv_obj_set_y(ui_TextArea1, -12);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");

    ui_Keyboard1 = lv_keyboard_create(ui_SerialTool);
    lv_obj_set_width(ui_Keyboard1, 239);
    lv_obj_set_height(ui_Keyboard1, 94);
    lv_obj_set_x(ui_Keyboard1, -37);
    lv_obj_set_y(ui_Keyboard1, 71);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_Button6 = lv_btn_create(ui_SerialTool);
    lv_obj_set_width(ui_Button6, 62);
    lv_obj_set_height(ui_Button6, 39);
    lv_obj_set_x(ui_Button6, 123);
    lv_obj_set_y(ui_Button6, 92);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_SerialTool);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 123);
    lv_obj_set_y(ui_Label9, 93);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "back");

    ui_Spinner1 = lv_spinner_create(ui_SerialTool, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 49);
    lv_obj_set_height(ui_Spinner1, 59);
    lv_obj_set_x(ui_Spinner1, 125);
    lv_obj_set_y(ui_Spinner1, 46);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_keyboard_set_textarea(ui_Keyboard1, ui_TextArea1);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label9, ui_event_Label9, LV_EVENT_ALL, NULL);

}

void ui_SerialTool_screen_destroy(void)
{
    if(ui_SerialTool) lv_obj_del(ui_SerialTool);

    // NULL screen variables
    ui_SerialTool = NULL;
    ui_PanelRX = NULL;
    ui_labelrx = NULL;
    ui_TextArea1 = NULL;
    ui_Keyboard1 = NULL;
    ui_Button6 = NULL;
    ui_Label9 = NULL;
    ui_Spinner1 = NULL;

}