// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SERIALTOOL_H
#define UI_SERIALTOOL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SerialTool
extern void ui_SerialTool_screen_init(void);
extern void ui_SerialTool_screen_destroy(void);
extern lv_obj_t * ui_SerialTool;
extern lv_obj_t * ui_PanelRX;
extern lv_obj_t * ui_labelrx;
extern lv_obj_t * ui_TextArea1;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern void ui_event_Label9(lv_event_t * e);
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Spinner1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

